language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t ryurikk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ryurikk/react-test npm test -- --coverage

after_success:
  - docker build -t ryurikk/multi-client ./client
  - docker build -t ryurikk/multi-nginx ./nginx
  - docker build -t ryurikk/multi-server ./server
  - docker build -t ryurikk/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to DockerHub
  - docker push ryurikk/multi-client
  - docker push ryurikk/multi-nginx
  - docker push ryurikk/multi-server
  - docker push ryurikk/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-116361194595"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY